export const mockProducts = [
  {
    id: 1,
    img: "https://via.placeholder.com/150",
    originalPrice: 2000,
    sellingPrice: 6000,
    categories: "GroupA",
    quantities: 10,
    brand: "test1",
  },
  {
    id: 2,
    img: "https://via.placeholder.com/150",
    originalPrice: 2500,
    sellingPrice: 6500,
    categories: "GroupA",
    quantities: 8,
    brand: "test1",
  },
  {
    id: 3,
    img: "https://via.placeholder.com/150",
    originalPrice: 3000,
    sellingPrice: 7000,
    categories: "GroupB",
    quantities: 5,
    brand: "test1",
  },
  {
    id: 4,
    img: "https://via.placeholder.com/150",
    originalPrice: 1800,
    sellingPrice: 5500,
    categories: "GroupB",
    quantities: 12,
  },
  {
    id: 5,
    img: "https://via.placeholder.com/150",
    originalPrice: 4000,
    sellingPrice: 9000,
    categories: "GroupC",
    quantities: 7,
  },
  {
    id: 6,
    img: "https://via.placeholder.com/150",
    originalPrice: 3200,
    sellingPrice: 7600,
    categories: "GroupC",
    quantities: 9,
  },
  {
    id: 7,
    img: "https://via.placeholder.com/150",
    originalPrice: 3200,
    sellingPrice: 7600,
    categories: "GroupD",
    quantities: 9,
  },
  {
    id: 8,
    img: "https://via.placeholder.com/150",
    originalPrice: 3200,
    sellingPrice: 7600,
    categories: "GroupE",
    quantities: 9,
  },
  {
    id: 9,
    img: "https://via.placeholder.com/150",
    originalPrice: 3200,
    sellingPrice: 7600,
    categories: "GroupF",
    quantities: 9,
  },
  {
    id: 10,
    img: "https://via.placeholder.com/150",
    originalPrice: 3200,
    sellingPrice: 7600,
    categories: "GroupG",
    quantities: 9,
  },
  {
    id: 11,
    img: "https://via.placeholder.com/150",
    originalPrice: 3200,
    sellingPrice: 7600,
    categories: "GroupH",
    quantities: 9,
  },
  {
    id: 12,
    img: "https://via.placeholder.com/150",
    originalPrice: 3200,
    sellingPrice: 7600,
    categories: "GroupI",
    quantities: 9,
  },
  {
    id: 13,
    img: "https://via.placeholder.com/150",
    originalPrice: 3200,
    sellingPrice: 7600,
    categories: "GroupI",
    quantities: 9,
  },
  {
    id: 14,
    img: "https://via.placeholder.com/150",
    originalPrice: 3200,
    sellingPrice: 7600,
    categories: "GroupD",
    quantities: 9,
  },
];
